server:
  port: 81


eureka:
  client:
    fetch-registry: true      #是否从EurekaServer 抓取已有的注册信息，默认为true.单点无所谓，集群必须设置为true 才能配合ribbon使用负载均衡
    register-with-eureka: true # 表示是否将自己注册进eurekaServer 默认为true
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
spring:
  application:
    name: cloud-order-service #服务名