server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #eureka 服务端的实例名称

  client:
    register-with-eureka: false #false 表示不向注册中心注册自己
    fetch-registry: false  #false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务

    serviceUrl:
     defaultZone: http://eureka7002.com:7002/eureka/
#     defaultZone: http://eureka7001.com:7001/eureka/
    #置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址

#  server:
#    enable-self-preservation: false  #自我保护
#    eviction-interval-timer-in-ms: 2000 #

